version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/*"
    versions:
    - ">=8"
  - dependency-name: "@angular-devkit/build-ng-packagr"
    versions:
    - ">=0.800"
  - dependency-name: typescript
    versions:
    - ">= 0"
  - dependency-name: "@types/node"
    versions:
    - ">=11"
  commit-message:
    prefix: chore
    include: scope
